chore: add up to date actions
ForGloryStudyGroup/hospital-sys-backend pull request #1
Opened 2024-06-06 17:18 UTC by ThreeOneOneZero

2024-06-10 16:45 UTC, ValchanOficial commented
@ThreeOneOneZero se puder add a verificação pelas configs:
Doc: https://docs.github.com/pt/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches#about-branch-protection-settings

2024-06-10 16:46 UTC, ValchanOficial requested changes
https://docs.github.com/pt/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches

2024-06-10 17:12 UTC, ThreeOneOneZero commented
> @ThreeOneOneZero se puder add a verificação pelas configs: Doc: https://docs.github.com/pt/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches#about-branch-protection-settings

Então, eu já coloquei pelas configs:
![image](https://github.com/ForGloryStudyGroup/hospital-sys-backend/assets/123659136/3c1763a2-3798-4009-a57f-12f240741175)

Pelo que vi precisa adicionar uma verificação, ou a configuração não irá surtir efeito.
Caso tenha outra maneira, só mandar.
![image](https://github.com/ForGloryStudyGroup/hospital-sys-backend/assets/123659136/b8a56afe-b32f-42c0-b88a-deb7d6e1e1df)

2024-06-11 01:07 UTC, ValchanOficial commented
Habilitei o SonarCloud nos repositórios e adicionei a secret SONAR_TOKEN em ambos

2024-06-15 20:01 UTC, ValchanOficial requested changes
Adiciona no yaml o SonarCloud o/
```
name: Workflow
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
```
**sonar-project.properties** na raiz do projeto
```
sonar.projectKey=ForGloryStudyGroup_hospital-sys-backend
sonar.organization=forglory

sonar.projectName=hospital-sys-backend
sonar.projectVersion=1.0

sonar.sources=.

sonar.sourceEncoding=UTF-8
sonar.inclusions=**/*.js, **/*.ts
# sonar.exclusions=**/*.spec.js, **/*.spec.ts

# TODO ajustar quando for configurar testes
# sonar.tests=.
# sonar.test.inclusions=**/*.spec.js, **/*.spec.ts
# sonar.javascript.lcov.reportPaths=coverage/lcov.info
```

2024-06-22 19:35 UTC, ValchanOficial approved these changes

2024-06-22 19:38 UTC, merged